language: node_js
node_js:
  - "12"
cache: npm

before_script:
- npm i
- npm i codecov -g
- npm run build

script:
- npm run lint
- npm test

notifications:
  email: false
  notifications:
    slack: amitum:wNVxxxvZmHVaX8qI28xzrXlU
    on_success: change

after_success:
  - codecov
